import type { FieldOption, ModuleConfig, UserRole } from "./types";

export const roleLabels: Record<UserRole, string> = {
  owner: "Owner / Admin",
  manager: "Manager",
  staff: "Staff",
  accountant: "Accountant",
};

export const allRoles: UserRole[] = ["owner", "manager", "staff", "accountant"];
export const financeRoles: UserRole[] = ["owner", "manager", "accountant"];
export const operationRoles: UserRole[] = ["owner", "manager", "staff"];

export const unitOptions: FieldOption[] = [
  { label: "ชิ้น", value: "ชิ้น" },
  { label: "อัน", value: "อัน" },
  { label: "ชุด", value: "ชุด" },
  { label: "คู่", value: "คู่" },
  { label: "ข้าง", value: "ข้าง" },
  { label: "เส้น", value: "เส้น" },
  { label: "กล่อง", value: "กล่อง" },
  { label: "กระป๋อง", value: "กระป๋อง" },
  { label: "ลิตร", value: "ลิตร" },
  { label: "เมตร", value: "เมตร" },
  { label: "กิโลกรัม", value: "กิโลกรัม" },
  { label: "อื่น ๆ", value: "อื่น ๆ" },
];

export const vehicleBrandOptions: FieldOption[] = [
  "Toyota",
  "Honda",
  "Isuzu",
  "Mitsubishi",
  "Nissan",
  "Mazda",
  "Ford",
  "Chevrolet",
  "Suzuki",
  "MG",
  "Hyundai",
  "Kia",
  "Mercedes-Benz",
  "BMW",
  "Volvo",
  "Hino",
  "Fuso",
  "UD Trucks",
  "อื่น ๆ",
].map((value) => ({ label: value, value }));

export const vehicleModelOptions: FieldOption[] = [
  "Hilux Revo",
  "Hilux Vigo",
  "Fortuner",
  "Yaris",
  "Vios",
  "Corolla Altis",
  "Camry",
  "City",
  "Civic",
  "CR-V",
  "Jazz",
  "D-Max",
  "MU-X",
  "Triton",
  "Pajero Sport",
  "Navara",
  "Almera",
  "March",
  "BT-50",
  "Ranger",
  "Everest",
  "Colorado",
  "Swift",
  "Ciaz",
  "ZS",
  "HS",
  "H-1",
  "Carnival",
  "อื่น ๆ",
].map((value) => ({ label: value, value }));

export const vehicleYearOptions: FieldOption[] = Array.from({ length: 37 }, (_, index) => {
  const value = String(2026 - index);
  return { label: value, value };
});

export const repairStatuses: FieldOption[] = [
  { label: "รับรถแล้ว", value: "received" },
  { label: "รอตรวจเช็ก", value: "diagnosing" },
  { label: "เสนอราคาแล้ว", value: "quoted" },
  { label: "รอลูกค้าอนุมัติ", value: "waiting_approval" },
  { label: "กำลังซ่อม", value: "in_progress" },
  { label: "รออะไหล่", value: "waiting_parts" },
  { label: "ซ่อมเสร็จ", value: "completed" },
  { label: "รอชำระเงิน", value: "waiting_payment" },
  { label: "ส่งมอบรถแล้ว", value: "delivered" },
  { label: "ยกเลิก", value: "cancelled" },
];

export const quoteStatuses: FieldOption[] = [
  { label: "ร่าง", value: "draft" },
  { label: "ส่งให้ลูกค้าแล้ว", value: "sent" },
  { label: "อนุมัติแล้ว", value: "approved" },
  { label: "ไม่อนุมัติ", value: "rejected" },
  { label: "ยกเลิก", value: "cancelled" },
];

export const invoiceStatuses: FieldOption[] = [
  { label: "ยังไม่ชำระ", value: "unpaid" },
  { label: "ชำระบางส่วน", value: "partial" },
  { label: "ชำระครบแล้ว", value: "paid" },
  { label: "เกินกำหนด", value: "overdue" },
  { label: "ยกเลิก", value: "cancelled" },
];

export const paymentMethods: FieldOption[] = [
  { label: "เงินสด", value: "cash" },
  { label: "โอนเงิน", value: "transfer" },
  { label: "QR Payment", value: "qr" },
  { label: "อื่น ๆ", value: "other" },
];

export const incomeCategories: FieldOption[] = [
  { label: "รายได้จากงานซ่อม", value: "repair_service" },
  { label: "รายได้จากขายอะไหล่", value: "parts_sale" },
  { label: "รายได้อื่น ๆ", value: "other" },
];

export const expenseCategories: FieldOption[] = [
  { label: "ซื้ออะไหล่", value: "parts_purchase" },
  { label: "ค่าแรง", value: "labor" },
  { label: "ค่าอุปกรณ์", value: "equipment" },
  { label: "ค่าไฟ", value: "electricity" },
  { label: "ค่าน้ำ", value: "water" },
  { label: "ค่าเช่า", value: "rent" },
  { label: "ค่าเดินทาง", value: "travel" },
  { label: "ค่าใช้จ่ายอื่น ๆ", value: "other" },
];

export const menuItems = [
  { label: "Dashboard", href: "/dashboard", icon: "LayoutDashboard", roles: allRoles },
  { label: "แจ้งเตือน", href: "/notifications", icon: "Bell", roles: allRoles },
  { label: "อนุมัติ", href: "/approvals", icon: "ClipboardCheck", roles: ["owner", "manager"] as UserRole[] },
  { label: "ลูกค้า", href: "/customers", icon: "Users", roles: allRoles },
  { label: "รถยนต์", href: "/vehicles", icon: "Car", roles: allRoles },
  { label: "งานซ่อม", href: "/repair-jobs", icon: "Wrench", roles: allRoles },
  { label: "อะไหล่ / สต๊อก", href: "/parts", icon: "Package", roles: allRoles },
  { label: "ซื้ออะไหล่", href: "/purchases", icon: "ShoppingCart", roles: financeRoles },
  { label: "Supplier", href: "/suppliers", icon: "Truck", roles: financeRoles },
  { label: "ใบเสนอราคา", href: "/quotations", icon: "FileText", roles: financeRoles },
  { label: "ใบแจ้งหนี้", href: "/invoices", icon: "ReceiptText", roles: financeRoles },
  { label: "ใบวางบิล", href: "/billing-statements", icon: "FileText", roles: financeRoles },
  { label: "ใบเสร็จรับเงิน", href: "/receipts", icon: "BadgeDollarSign", roles: financeRoles },
  { label: "บิลเงินสด", href: "/cash-bills", icon: "WalletCards", roles: financeRoles },
  { label: "รายรับ", href: "/income", icon: "TrendingUp", roles: financeRoles },
  { label: "รายจ่าย", href: "/expenses", icon: "TrendingDown", roles: financeRoles },
  { label: "รายงาน", href: "/reports", icon: "BarChart3", roles: financeRoles },
  { label: "Activity Log", href: "/activity-logs", icon: "ClipboardList", roles: financeRoles },
  { label: "Backup / Export", href: "/backup", icon: "DatabaseBackup", roles: ["owner"] as UserRole[] },
  { label: "ตั้งค่ากิจการ", href: "/settings", icon: "Settings", roles: ["owner"] as UserRole[] },
  { label: "จัดการผู้ใช้", href: "/users", icon: "ShieldCheck", roles: ["owner"] as UserRole[] },
  { label: "คู่มือการใช้งาน", href: "/manual", icon: "BookOpenText", roles: allRoles, section: "bottom" },
];

export const modules: Record<string, ModuleConfig> = {
  customers: {
    key: "customers",
    table: "customers",
    title: "ลูกค้า",
    description: "จัดการข้อมูลลูกค้า ประวัติรถ และยอดค้างชำระ",
    createLabel: "เพิ่มลูกค้า",
    policy: { read: allRoles, write: allRoles, delete: ["owner", "manager"] },
    searchFields: ["full_name", "phone", "line_id"],
    columns: [
      { key: "full_name", label: "ชื่อลูกค้า" },
      { key: "phone", label: "เบอร์โทร" },
      { key: "line_id", label: "LINE" },
      { key: "outstanding_balance", label: "ยอดค้าง", type: "money" },
      { key: "created_at", label: "วันที่สร้าง", type: "date" },
    ],
    fields: [
      { name: "full_name", label: "ชื่อลูกค้า", type: "text", required: true },
      { name: "phone", label: "เบอร์โทร", type: "text", required: true },
      { name: "address", label: "ที่อยู่", type: "textarea" },
      { name: "line_id", label: "LINE / ช่องทางติดต่อ", type: "text" },
      { name: "notes", label: "หมายเหตุ", type: "textarea" },
    ],
  },
  vehicles: {
    key: "vehicles",
    table: "vehicles",
    title: "รถยนต์",
    description: "ทะเบียน เจ้าของรถ และประวัติซ่อมแยกตามคัน",
    createLabel: "เพิ่มรถ",
    policy: { read: allRoles, write: operationRoles, delete: ["owner", "manager"] },
    searchFields: ["license_plate", "brand", "model", "province"],
    columns: [
      { key: "license_plate", label: "ทะเบียน" },
      { key: "province", label: "จังหวัด" },
      { key: "brand", label: "ยี่ห้อ" },
      { key: "model", label: "รุ่น" },
      { key: "mileage", label: "เลขไมล์" },
    ],
    fields: [
      { name: "customer_id", label: "เจ้าของรถ", type: "select", optionsKey: "customers", required: true },
      { name: "license_plate", label: "ทะเบียนรถ", type: "text", required: true },
      { name: "province", label: "จังหวัดทะเบียน", type: "text" },
      { name: "brand", label: "ยี่ห้อ", type: "text", required: true, options: vehicleBrandOptions },
      { name: "model", label: "รุ่น", type: "text", required: true, options: vehicleModelOptions },
      { name: "year", label: "ปีรถ", type: "number", options: vehicleYearOptions },
      { name: "color", label: "สี", type: "text" },
      { name: "mileage", label: "เลขไมล์", type: "number" },
      { name: "vin", label: "เลขตัวถัง", type: "text" },
      { name: "engine_no", label: "เลขเครื่องยนต์", type: "text" },
      { name: "notes", label: "หมายเหตุ", type: "textarea" },
    ],
  },
  "repair-jobs": {
    key: "repair-jobs",
    table: "repair_jobs",
    title: "งานซ่อม",
    description: "เปิดใบรับรถ ติดตามสถานะ แนบรูป และบันทึก timeline",
    createLabel: "เปิดงานซ่อม",
    numberPrefix: "JOB",
    policy: { read: allRoles, write: operationRoles, delete: ["owner", "manager"] },
    searchFields: ["job_number", "reported_problem", "status"],
    columns: [
      { key: "job_number", label: "เลขงาน" },
      { key: "received_at", label: "วันที่รับรถ", type: "date" },
      { key: "status", label: "สถานะ", type: "badge" },
      { key: "reported_problem", label: "อาการเสีย" },
      { key: "estimated_total", label: "ยอดประมาณการ", type: "money" },
    ],
    fields: [
      { name: "received_at", label: "วันที่รับรถ", type: "date", required: true },
      { name: "customer_id", label: "ลูกค้า", type: "select", optionsKey: "customers", required: true },
      { name: "vehicle_id", label: "รถ", type: "select", optionsKey: "vehicles", required: true },
      { name: "reported_problem", label: "อาการเสียที่ลูกค้าแจ้ง", type: "textarea", required: true },
      { name: "preliminary_check", label: "รายการตรวจเช็กเบื้องต้น", type: "textarea" },
      { name: "intake_mileage", label: "เลขไมล์ตอนรับรถ", type: "number" },
      { name: "valuables", label: "ของมีค่าในรถ", type: "textarea" },
      { name: "status", label: "สถานะงานซ่อม", type: "select", options: repairStatuses, required: true },
      { name: "internal_notes", label: "หมายเหตุภายใน", type: "textarea" },
    ],
  },
  parts: {
    key: "parts",
    table: "parts",
    title: "อะไหล่ / สต๊อก",
    description: "ควบคุมสต๊อก ราคาทุน ราคาขาย และแจ้งเตือนสินค้าใกล้หมด",
    createLabel: "เพิ่มอะไหล่",
    policy: { read: allRoles, write: financeRoles, delete: ["owner", "manager"] },
    searchFields: ["part_code", "name"],
    columns: [
      { key: "part_code", label: "รหัส" },
      { key: "name", label: "ชื่ออะไหล่" },
      { key: "sale_price", label: "ราคาขาย", type: "money" },
      { key: "quantity_on_hand", label: "คงเหลือ" },
      { key: "low_stock_threshold", label: "จุดเตือน" },
    ],
    fields: [
      { name: "part_code", label: "รหัสอะไหล่", type: "text", required: true },
      { name: "name", label: "ชื่ออะไหล่", type: "text", required: true },
      { name: "category_id", label: "หมวดหมู่", type: "select", optionsKey: "partCategories" },
      { name: "cost_price", label: "ราคาทุน", type: "number", required: true, step: "0.01" },
      { name: "sale_price", label: "ราคาขาย", type: "number", required: true, step: "0.01" },
      { name: "quantity_on_hand", label: "จำนวนคงเหลือ", type: "number", required: true },
      { name: "unit", label: "หน่วยนับ", type: "text", required: true, options: unitOptions },
      { name: "supplier_id", label: "Supplier", type: "select", optionsKey: "suppliers" },
      { name: "low_stock_threshold", label: "จุดแจ้งเตือน", type: "number" },
      { name: "notes", label: "หมายเหตุ", type: "textarea" },
    ],
  },
  purchases: {
    key: "purchases",
    table: "purchases",
    title: "ซื้ออะไหล่",
    description: "บันทึกซื้ออะไหล่ รับสินค้าเข้าสต๊อก และติดตามเจ้าหนี้ Supplier",
    createLabel: "บันทึกซื้ออะไหล่",
    numberPrefix: "PO",
    policy: { read: financeRoles, write: financeRoles, delete: ["owner", "manager"] },
    searchFields: ["purchase_no", "payment_status", "notes"],
    columns: [
      { key: "purchase_no", label: "เลขที่ใบซื้อ" },
      { key: "purchased_at", label: "วันที่ซื้อ", type: "date" },
      { key: "payment_status", label: "สถานะ", type: "badge" },
      { key: "balance_due", label: "ค้างชำระ", type: "money" },
      { key: "total", label: "ยอดรวม", type: "money" },
    ],
    fields: [],
  },
  suppliers: {
    key: "suppliers",
    table: "suppliers",
    title: "Supplier / เจ้าหนี้",
    description: "ข้อมูลร้านอะไหล่ เครดิตคงค้าง และประวัติซื้อ",
    createLabel: "เพิ่ม Supplier",
    policy: { read: financeRoles, write: financeRoles, delete: ["owner", "manager"] },
    searchFields: ["name", "phone"],
    columns: [
      { key: "name", label: "ชื่อร้าน / บริษัท" },
      { key: "phone", label: "เบอร์โทร" },
      { key: "credit_balance", label: "เครดิตคงค้าง", type: "money" },
      { key: "created_at", label: "วันที่สร้าง", type: "date" },
    ],
    fields: [
      { name: "name", label: "ชื่อร้าน / บริษัท", type: "text", required: true },
      { name: "phone", label: "เบอร์โทร", type: "text" },
      { name: "address", label: "ที่อยู่", type: "textarea" },
      { name: "regular_items", label: "รายการอะไหล่ที่ซื้อประจำ", type: "textarea" },
      { name: "credit_balance", label: "เครดิตคงค้าง", type: "number", step: "0.01" },
      { name: "notes", label: "หมายเหตุ", type: "textarea" },
    ],
  },
  quotations: {
    key: "quotations",
    table: "quotations",
    title: "ใบเสนอราคา",
    description: "สร้างใบเสนอราคาจากงานซ่อมพร้อมรายการค่าแรงและอะไหล่",
    createLabel: "สร้างใบเสนอราคา",
    numberPrefix: "QT",
    policy: { read: financeRoles, write: financeRoles, delete: ["owner", "manager"] },
    searchFields: ["quotation_no", "status", "notes"],
    columns: [
      { key: "quotation_no", label: "เลขที่" },
      { key: "issued_at", label: "วันที่ออก", type: "date" },
      { key: "status", label: "สถานะ", type: "badge" },
      { key: "total", label: "ยอดสุทธิ", type: "money" },
    ],
    fields: [
      { name: "issued_at", label: "วันที่ออกเอกสาร", type: "date", required: true },
      { name: "customer_id", label: "ลูกค้า", type: "select", optionsKey: "customers", required: true },
      { name: "vehicle_id", label: "รถ", type: "select", optionsKey: "vehicles" },
      { name: "repair_job_id", label: "อ้างอิงงานซ่อม", type: "select", optionsKey: "repairJobs" },
      { name: "status", label: "สถานะ", type: "select", options: quoteStatuses, required: true },
      { name: "discount", label: "ส่วนลดรวม", type: "number", step: "0.01" },
      { name: "show_payment_info", label: "แสดงข้อมูลบัญชีธนาคารบนเอกสาร", type: "checkbox" },
      { name: "show_paid_stamp", label: "Stamp จ่ายแล้วบนเอกสาร", type: "checkbox" },
      { name: "items", label: "รายการซ่อมและอะไหล่", type: "line-items", required: true },
      { name: "notes", label: "หมายเหตุ", type: "textarea" },
      { name: "terms", label: "เงื่อนไข", type: "textarea" },
    ],
  },
  invoices: {
    key: "invoices",
    table: "invoices",
    title: "ใบแจ้งหนี้",
    description: "วางบิล รับชำระบางส่วน และติดตามยอดค้าง",
    createLabel: "สร้างใบแจ้งหนี้",
    numberPrefix: "INV",
    policy: { read: financeRoles, write: financeRoles, delete: ["owner", "manager"] },
    searchFields: ["invoice_no", "payment_status", "notes"],
    columns: [
      { key: "invoice_no", label: "เลขที่" },
      { key: "issued_at", label: "วันที่ออก", type: "date" },
      { key: "due_at", label: "ครบกำหนด", type: "date" },
      { key: "payment_status", label: "สถานะ", type: "badge" },
      { key: "balance_due", label: "ยอดค้าง", type: "money" },
      { key: "total", label: "ยอดสุทธิ", type: "money" },
    ],
    fields: [
      { name: "issued_at", label: "วันที่ออก", type: "date", required: true },
      { name: "due_at", label: "วันครบกำหนด", type: "date", required: true },
      { name: "customer_id", label: "ลูกค้า", type: "select", optionsKey: "customers", required: true },
      { name: "vehicle_id", label: "รถ", type: "select", optionsKey: "vehicles" },
      { name: "repair_job_id", label: "อ้างอิงงานซ่อม", type: "select", optionsKey: "repairJobs" },
      { name: "payment_status", label: "สถานะการชำระเงิน", type: "select", options: invoiceStatuses, required: true },
      { name: "discount", label: "ส่วนลดรวม", type: "number", step: "0.01" },
      { name: "show_payment_info", label: "แสดงข้อมูลบัญชีธนาคารบนเอกสาร", type: "checkbox" },
      { name: "show_paid_stamp", label: "Stamp จ่ายแล้วบนเอกสาร", type: "checkbox" },
      { name: "items", label: "รายการซ่อมและอะไหล่", type: "line-items", required: true },
      { name: "notes", label: "หมายเหตุ", type: "textarea" },
    ],
  },
  "billing-statements": {
    key: "billing-statements",
    table: "billing_statements",
    title: "ใบวางบิล",
    description: "รวบรวมใบแจ้งหนี้หลายรายการเพื่อวางบิลให้ลูกค้าในเอกสารเดียว",
    createLabel: "สร้างใบวางบิล",
    numberPrefix: "BS",
    policy: { read: financeRoles, write: financeRoles, delete: ["owner", "manager"] },
    searchFields: ["billing_statement_no", "status", "notes"],
    columns: [
      { key: "billing_statement_no", label: "เลขที่" },
      { key: "issued_at", label: "วันที่ออก", type: "date" },
      { key: "due_at", label: "ครบกำหนด", type: "date" },
      { key: "status", label: "สถานะ", type: "badge" },
      { key: "total", label: "ยอดวางบิล", type: "money" },
    ],
    fields: [],
  },
  receipts: {
    key: "receipts",
    table: "receipts",
    title: "ใบเสร็จรับเงิน",
    description: "ออกใบเสร็จและบันทึกรายรับอัตโนมัติ",
    createLabel: "ออกใบเสร็จ",
    numberPrefix: "RC",
    policy: { read: financeRoles, write: financeRoles, delete: ["owner", "manager"] },
    searchFields: ["receipt_no", "customer_phone", "payment_method", "notes"],
    columns: [
      { key: "receipt_no", label: "เลขที่" },
      { key: "received_at", label: "วันที่รับเงิน", type: "date" },
      { key: "customer_phone", label: "เบอร์โทร" },
      { key: "payment_method", label: "ช่องทาง" },
      { key: "amount", label: "จำนวนเงิน", type: "money" },
    ],
    fields: [
      { name: "received_at", label: "วันที่รับเงิน", type: "date", required: true },
      { name: "invoice_id", label: "อ้างอิงใบแจ้งหนี้", type: "select", optionsKey: "invoices", required: true },
      { name: "customer_id", label: "ลูกค้า", type: "select", optionsKey: "customers", required: true },
      { name: "payment_method", label: "ช่องทางชำระเงิน", type: "select", options: paymentMethods, required: true },
      { name: "amount", label: "จำนวนเงินที่รับ", type: "number", required: true, step: "0.01" },
      { name: "show_payment_info", label: "แสดงข้อมูลบัญชีธนาคารบนเอกสาร", type: "checkbox" },
      { name: "show_paid_stamp", label: "Stamp จ่ายแล้วบนเอกสาร", type: "checkbox" },
      { name: "notes", label: "หมายเหตุ", type: "textarea" },
    ],
  },
  "cash-bills": {
    key: "cash-bills",
    table: "cash_bills",
    title: "บิลเงินสด",
    description: "ออกบิลด่วน รับเงินทันที บันทึกรายรับและประวัติไว้ในระบบ",
    createLabel: "ออกบิลเงินสด",
    numberPrefix: "CB",
    policy: { read: financeRoles, write: financeRoles, delete: ["owner", "manager"] },
    searchFields: ["cash_bill_no", "customer_name", "customer_phone", "vehicle_text", "notes"],
    columns: [
      { key: "cash_bill_no", label: "เลขที่" },
      { key: "issued_at", label: "วันที่ออก", type: "date" },
      { key: "customer_name", label: "ลูกค้า" },
      { key: "customer_phone", label: "เบอร์โทร" },
      { key: "payment_method", label: "ช่องทาง" },
      { key: "total", label: "ยอดสุทธิ", type: "money" },
    ],
    fields: [
      { name: "issued_at", label: "วันที่ออกบิล", type: "date" },
      { name: "customer_id", label: "ค้นหาลูกค้าในระบบ", type: "select", optionsKey: "customers" },
      { name: "customer_name", label: "ชื่อลูกค้า / ชื่อผู้จ่าย", type: "text" },
      { name: "customer_phone", label: "เบอร์โทร", type: "text" },
      { name: "customer_address", label: "ที่อยู่", type: "textarea" },
      { name: "vehicle_id", label: "ค้นหารถ / ทะเบียนในระบบ", type: "select", optionsKey: "vehicles" },
      { name: "repair_job_id", label: "อ้างอิงงานซ่อม", type: "select", optionsKey: "repairJobs" },
      { name: "vehicle_text", label: "ข้อมูลรถ / ทะเบียนแบบพิมพ์เอง", type: "text" },
      { name: "payment_method", label: "ช่องทางชำระเงิน", type: "select", options: paymentMethods },
      { name: "discount", label: "ส่วนลดรวม", type: "number", step: "0.01" },
      { name: "show_payment_info", label: "แสดงข้อมูลบัญชีธนาคารบนเอกสาร", type: "checkbox" },
      { name: "show_paid_stamp", label: "Stamp จ่ายแล้วบนเอกสาร", type: "checkbox" },
      { name: "items", label: "รายการบิลเงินสด", type: "line-items" },
      { name: "notes", label: "หมายเหตุ", type: "textarea" },
    ],
  },
  income: {
    key: "income",
    table: "income_records",
    title: "รายรับ",
    description: "บันทึกรายรับจากงานซ่อม ขายอะไหล่ และรายได้อื่น",
    createLabel: "บันทึกรายรับ",
    policy: { read: financeRoles, write: financeRoles, delete: ["owner", "manager", "accountant"] },
    searchFields: ["description", "category", "payment_method"],
    columns: [
      { key: "recorded_at", label: "วันที่", type: "date" },
      { key: "category", label: "หมวดหมู่" },
      { key: "description", label: "รายละเอียด" },
      { key: "amount", label: "จำนวนเงิน", type: "money" },
      { key: "payment_method", label: "ช่องทาง" },
    ],
    fields: [
      { name: "recorded_at", label: "วันที่", type: "date", required: true },
      { name: "category", label: "หมวดหมู่", type: "select", options: incomeCategories, required: true },
      { name: "description", label: "รายละเอียด", type: "textarea", required: true },
      { name: "amount", label: "จำนวนเงิน", type: "number", required: true, step: "0.01" },
      { name: "payment_method", label: "ช่องทางรับเงิน", type: "select", options: paymentMethods, required: true },
      { name: "reference_no", label: "อ้างอิงเอกสาร", type: "text" },
    ],
  },
  expenses: {
    key: "expenses",
    table: "expense_records",
    title: "รายจ่าย",
    description: "บันทึกค่าใช้จ่ายและแนบอ้างอิง Supplier",
    createLabel: "บันทึกรายจ่าย",
    policy: { read: financeRoles, write: financeRoles, delete: ["owner", "manager", "accountant"] },
    searchFields: ["description", "category", "payment_method"],
    columns: [
      { key: "recorded_at", label: "วันที่", type: "date" },
      { key: "category", label: "หมวดหมู่" },
      { key: "description", label: "รายละเอียด" },
      { key: "amount", label: "จำนวนเงิน", type: "money" },
      { key: "payment_method", label: "ช่องทาง" },
    ],
    fields: [
      { name: "recorded_at", label: "วันที่", type: "date", required: true },
      { name: "category", label: "หมวดหมู่", type: "select", options: expenseCategories, required: true },
      { name: "description", label: "รายละเอียด", type: "textarea", required: true },
      { name: "amount", label: "จำนวนเงิน", type: "number", required: true, step: "0.01" },
      { name: "payment_method", label: "ช่องทางจ่าย", type: "select", options: paymentMethods, required: true },
      { name: "supplier_id", label: "Supplier", type: "select", optionsKey: "suppliers" },
      { name: "receipt_image_url", label: "ลิงก์รูปใบเสร็จ", type: "text" },
    ],
  },
  settings: {
    key: "settings",
    table: "company_settings",
    title: "ตั้งค่ากิจการ",
    description: "ข้อมูลอู่ โลโก้ Prefix เอกสาร และข้อความท้ายเอกสาร",
    createLabel: "บันทึกข้อมูลกิจการ",
    policy: { read: allRoles, write: ["owner"], delete: ["owner"] },
    searchFields: ["company_name", "phone", "line_id"],
    columns: [
      { key: "company_name", label: "ชื่อกิจการ" },
      { key: "phone", label: "เบอร์โทร" },
      { key: "line_id", label: "LINE" },
      { key: "updated_at", label: "อัปเดตล่าสุด", type: "date" },
    ],
    fields: [
      { name: "company_name", label: "ชื่อกิจการ", type: "text", required: true },
      { name: "logo_url", label: "โลโก้ URL", type: "text" },
      { name: "address", label: "ที่อยู่", type: "textarea" },
      { name: "phone", label: "เบอร์โทร", type: "text" },
      { name: "line_id", label: "LINE", type: "text" },
      { name: "document_footer", label: "ข้อความท้ายเอกสาร", type: "textarea" },
      { name: "quotation_prefix", label: "Prefix ใบเสนอราคา", type: "text", required: true },
      { name: "invoice_prefix", label: "Prefix ใบแจ้งหนี้", type: "text", required: true },
      { name: "receipt_prefix", label: "Prefix ใบเสร็จ", type: "text", required: true },
      { name: "repair_job_prefix", label: "Prefix งานซ่อม", type: "text", required: true },
      { name: "cash_bill_prefix", label: "Prefix บิลเงินสด", type: "text", required: true },
      { name: "bank_name", label: "ชื่อธนาคาร", type: "text" },
      { name: "bank_logo_url", label: "โลโก้ธนาคาร URL", type: "text" },
      { name: "bank_account_number", label: "เลขที่บัญชี", type: "text" },
      { name: "bank_account_name", label: "ชื่อบัญชี", type: "text" },
    ],
  },
  users: {
    key: "users",
    table: "profiles",
    title: "จัดการผู้ใช้",
    description: "กำหนด role และสถานะผู้ใช้งาน",
    createLabel: "เพิ่มผู้ใช้",
    allowCreate: false,
    policy: { read: ["owner"], write: ["owner"], delete: ["owner"] },
    searchFields: ["full_name", "email", "role"],
    columns: [
      { key: "full_name", label: "ชื่อ" },
      { key: "email", label: "อีเมล" },
      { key: "role", label: "Role", type: "badge" },
      { key: "is_active", label: "ใช้งาน" },
      { key: "updated_at", label: "อัปเดตล่าสุด", type: "date" },
    ],
    fields: [
      { name: "full_name", label: "ชื่อ", type: "text", required: true },
      { name: "email", label: "อีเมล", type: "text", required: true },
      { name: "role", label: "Role", type: "select", options: allRoles.map((role) => ({ label: role, value: role })), required: true },
      { name: "is_active", label: "สถานะใช้งาน true/false", type: "text", required: true },
    ],
  },
};
